version: "3.3"

services:
  laravel:
    build: .
    volumes:
      - ./laravel:/var/www/html

  webserver:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./laravel:/code:ro
      - ./config/default.conf:/etc/nginx/conf.d/default.conf:ro

    depends_on:
      - php-1
      - php-2
      - php-3

  php-1:
    image: php:7.2-fpm
    ports:
      - 9000
    volumes:
      - ./laravel:/var/www/html
      - ./config/session.ini:/usr/local/etc/php/conf.d/session.ini:ro
    depends_on:
      - redis

  php-2:
    image: php:7.2-fpm
    ports:
      - 9000
    volumes:
      - ./laravel:/var/www/html
      - ./config/session.ini:/usr/local/etc/php/conf.d/session.ini:ro
    depends_on:
      - redis

  php-3:
    image: php:7.2-fpm
    ports:
      - 9000
    volumes:
      - ./laravel:/var/www/html
      - ./config/session.ini:/usr/local/etc/php/conf.d/session.ini:ro
    depends_on:
      - redis

  redis:
    image: redis:3.2
